from . import ts_device_category
from . import ts_device
from . import ts_device_branch
from . import ts_device_move
from . import ts_device_inventory
from . import ts_device_brand
from . import ts_device_model
from . import ts_device_branch_sync_settings
from . import ts_device_scrap_reason
from . import device_reports
